apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-exporter-1-pv-claim
  labels:
    app: nfs-exporter
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
