apiVersion: v1
kind: Service
metadata:
  name: nfs-exporter-1
spec:
  type: NodePort
  ports:
    - port: 111
      protocol: UDP
      nodePort: 30911
    - port: 2049
      nodePort: 30949
      protocol: 2049
  selector:
    app: nfs-exporter
