kind: Service
apiVersion: v1
metadata:
  name: nfs-exporter-1
spec:
  type: NodePort
  ports:
    - name: pmap
      port: 111
      protocol: UDP
      nodePort: 30911
    - name: nfs
      port: 2049
      nodePort: 30949
      protocol: TCP
  selector:
    app: nfs-exporter
    number: "1"
